import WordsmithReact = require('@wordsmith/react');
export const T : WordsmithReact.T;
export const LanguagePicker : WordsmithReact.LanguagePicker;
export const UT : WordsmithReact.UT;
export const useLanguages : WordsmithReact.useLanguages;
export const useLocale : WordsmithReact.useLocale;
export const useT : WordsmithReact.useT;
export const useTranslations : WordsmithReact.useTranslations;
export const useTX : WordsmithReact.useTX;
export const WSProvider : WordsmithReact.WSProvider;
